//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:trade_pilot_api_client/src/model/feedback.dart';
import 'package:built_collection/built_collection.dart';
import 'package:trade_pilot_api_client/src/model/fundamental_context.dart';
import 'package:trade_pilot_api_client/src/model/fundamental_citations.dart';
import 'package:trade_pilot_api_client/src/model/trade_plan.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'analysis.g.dart';

/// Analysis
///
/// Properties:
/// * [id] 
/// * [userId] 
/// * [instrument] 
/// * [timeframe] 
/// * [userInputContext] 
/// * [mode] 
/// * [validUntil] 
/// * [marketCondition] 
/// * [riskLevel] 
/// * [confidenceMin] 
/// * [confidenceMax] 
/// * [mainScenario] 
/// * [alternativeScenario] 
/// * [whyReason] 
/// * [failureConditions] 
/// * [baseCase] 
/// * [bullishScenario] 
/// * [bearishScenario] 
/// * [keyDriversTechnical] 
/// * [keyDriversFundamental] 
/// * [marketContext] 
/// * [invalidationConditions] 
/// * [uncertaintyNotes] 
/// * [tradingBias] - Directional bias. One of: bearish_strong, bearish, neutral, bullish, bullish_strong. Legacy values (strong_sell, sell, buy, strong_buy) may exist on older rows and are normalized client-side.
/// * [opportunity] 
/// * [risk] 
/// * [techBuyCount] - Snapshot of the technical-indicator buy tally captured at analysis time. Used to render the same Market Context Summary on the saved analysis page.
/// * [techSellCount] - Snapshot of the technical-indicator sell tally captured at analysis time.
/// * [techNeutralCount] - Snapshot of the technical-indicator neutral tally captured at analysis time.
/// * [tradePlan] - Structured trade plan with concrete buy and sell entry/SL/TP levels generated by the AI and anchored to the latest closing price. Nullable for legacy rows or when no anchor price was available.
/// * [fundamentalContext] - Snapshot of the news headlines + economic-calendar events the AI saw when this analysis was generated. Lets the saved-analysis page render the same fundamental context the model used. Nullable for legacy rows or when both upstream feeds were down.
/// * [fundamentalCitations] - Which news headlines + calendar events the AI actually cited in its narrative. Drives the inline source chips next to the AI's reasoning blocks (whyReason / keyDriversFundamental / marketContext). Nullable for legacy rows + analyses where the AI didn't lean on any fundamental input.
/// * [outcomeStatus] - After-the-fact resolution of the AI's trade plan. `pending` until the background resolver finishes scoring it; `tp1_hit`/`tp2_hit` if price reached the corresponding take-profit; `sl_hit` if the stop-loss was touched first; `expired` if the validity window passed with no trigger touched; `invalidated` when the plan levels were unparseable or internally inconsistent.
/// * [outcomeResolvedAt] - Timestamp the trigger (SL/TP1/TP2) fired on, or the validity-window end for `expired`. Null while outcomeStatus is `pending`.
/// * [outcomeCheckedAt] - When the background resolver last looked at this row. Null until the first resolver pass touches it.
/// * [userNote] - Private per-analysis trading journal note written by the owning user. Only populated by the single-analysis GET; the list endpoint exposes `hasNote` instead to keep payloads small. Never fed into the AI prompt.
/// * [userNoteUpdatedAt] - When `userNote` was last saved server-side. Null when no note has been written.
/// * [hasNote] - True when the user has written a non-empty `userNote` for this analysis. Returned by the list endpoint so the history page can show a 'journaled' icon without loading the full note body.
/// * [feedback] 
/// * [usefulCount] - Number of \"useful\" feedback rows for this analysis. Only populated by admin endpoints.
/// * [notUsefulCount] - Number of \"not_useful\" feedback rows for this analysis. Only populated by admin endpoints.
/// * [createdAt] 
@BuiltValue()
abstract class Analysis implements Built<Analysis, AnalysisBuilder> {
  @BuiltValueField(wireName: r'id')
  int get id;

  @BuiltValueField(wireName: r'userId')
  int get userId;

  @BuiltValueField(wireName: r'instrument')
  String get instrument;

  @BuiltValueField(wireName: r'timeframe')
  String get timeframe;

  @BuiltValueField(wireName: r'userInputContext')
  String? get userInputContext;

  @BuiltValueField(wireName: r'mode')
  AnalysisModeEnum get mode;
  // enum modeEnum {  beginner,  pro,  };

  @BuiltValueField(wireName: r'validUntil')
  DateTime get validUntil;

  @BuiltValueField(wireName: r'marketCondition')
  String? get marketCondition;

  @BuiltValueField(wireName: r'riskLevel')
  String? get riskLevel;

  @BuiltValueField(wireName: r'confidenceMin')
  int? get confidenceMin;

  @BuiltValueField(wireName: r'confidenceMax')
  int? get confidenceMax;

  @BuiltValueField(wireName: r'mainScenario')
  String? get mainScenario;

  @BuiltValueField(wireName: r'alternativeScenario')
  String? get alternativeScenario;

  @BuiltValueField(wireName: r'whyReason')
  String? get whyReason;

  @BuiltValueField(wireName: r'failureConditions')
  String? get failureConditions;

  @BuiltValueField(wireName: r'baseCase')
  String? get baseCase;

  @BuiltValueField(wireName: r'bullishScenario')
  String? get bullishScenario;

  @BuiltValueField(wireName: r'bearishScenario')
  String? get bearishScenario;

  @BuiltValueField(wireName: r'keyDriversTechnical')
  String? get keyDriversTechnical;

  @BuiltValueField(wireName: r'keyDriversFundamental')
  String? get keyDriversFundamental;

  @BuiltValueField(wireName: r'marketContext')
  String? get marketContext;

  @BuiltValueField(wireName: r'invalidationConditions')
  String? get invalidationConditions;

  @BuiltValueField(wireName: r'uncertaintyNotes')
  String? get uncertaintyNotes;

  /// Directional bias. One of: bearish_strong, bearish, neutral, bullish, bullish_strong. Legacy values (strong_sell, sell, buy, strong_buy) may exist on older rows and are normalized client-side.
  @BuiltValueField(wireName: r'tradingBias')
  String? get tradingBias;

  @BuiltValueField(wireName: r'opportunity')
  String? get opportunity;

  @BuiltValueField(wireName: r'risk')
  String? get risk;

  /// Snapshot of the technical-indicator buy tally captured at analysis time. Used to render the same Market Context Summary on the saved analysis page.
  @BuiltValueField(wireName: r'techBuyCount')
  int? get techBuyCount;

  /// Snapshot of the technical-indicator sell tally captured at analysis time.
  @BuiltValueField(wireName: r'techSellCount')
  int? get techSellCount;

  /// Snapshot of the technical-indicator neutral tally captured at analysis time.
  @BuiltValueField(wireName: r'techNeutralCount')
  int? get techNeutralCount;

  /// Structured trade plan with concrete buy and sell entry/SL/TP levels generated by the AI and anchored to the latest closing price. Nullable for legacy rows or when no anchor price was available.
  @BuiltValueField(wireName: r'tradePlan')
  TradePlan? get tradePlan;

  /// Snapshot of the news headlines + economic-calendar events the AI saw when this analysis was generated. Lets the saved-analysis page render the same fundamental context the model used. Nullable for legacy rows or when both upstream feeds were down.
  @BuiltValueField(wireName: r'fundamentalContext')
  FundamentalContext? get fundamentalContext;

  /// Which news headlines + calendar events the AI actually cited in its narrative. Drives the inline source chips next to the AI's reasoning blocks (whyReason / keyDriversFundamental / marketContext). Nullable for legacy rows + analyses where the AI didn't lean on any fundamental input.
  @BuiltValueField(wireName: r'fundamentalCitations')
  FundamentalCitations? get fundamentalCitations;

  /// After-the-fact resolution of the AI's trade plan. `pending` until the background resolver finishes scoring it; `tp1_hit`/`tp2_hit` if price reached the corresponding take-profit; `sl_hit` if the stop-loss was touched first; `expired` if the validity window passed with no trigger touched; `invalidated` when the plan levels were unparseable or internally inconsistent.
  @BuiltValueField(wireName: r'outcomeStatus')
  AnalysisOutcomeStatusEnum? get outcomeStatus;
  // enum outcomeStatusEnum {  pending,  tp1_hit,  tp2_hit,  sl_hit,  expired,  invalidated,  };

  /// Timestamp the trigger (SL/TP1/TP2) fired on, or the validity-window end for `expired`. Null while outcomeStatus is `pending`.
  @BuiltValueField(wireName: r'outcomeResolvedAt')
  DateTime? get outcomeResolvedAt;

  /// When the background resolver last looked at this row. Null until the first resolver pass touches it.
  @BuiltValueField(wireName: r'outcomeCheckedAt')
  DateTime? get outcomeCheckedAt;

  /// Private per-analysis trading journal note written by the owning user. Only populated by the single-analysis GET; the list endpoint exposes `hasNote` instead to keep payloads small. Never fed into the AI prompt.
  @BuiltValueField(wireName: r'userNote')
  String? get userNote;

  /// When `userNote` was last saved server-side. Null when no note has been written.
  @BuiltValueField(wireName: r'userNoteUpdatedAt')
  DateTime? get userNoteUpdatedAt;

  /// True when the user has written a non-empty `userNote` for this analysis. Returned by the list endpoint so the history page can show a 'journaled' icon without loading the full note body.
  @BuiltValueField(wireName: r'hasNote')
  bool? get hasNote;

  @BuiltValueField(wireName: r'feedback')
  Feedback? get feedback;

  /// Number of \"useful\" feedback rows for this analysis. Only populated by admin endpoints.
  @BuiltValueField(wireName: r'usefulCount')
  int? get usefulCount;

  /// Number of \"not_useful\" feedback rows for this analysis. Only populated by admin endpoints.
  @BuiltValueField(wireName: r'notUsefulCount')
  int? get notUsefulCount;

  @BuiltValueField(wireName: r'createdAt')
  DateTime get createdAt;

  Analysis._();

  factory Analysis([void updates(AnalysisBuilder b)]) = _$Analysis;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(AnalysisBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<Analysis> get serializer => _$AnalysisSerializer();
}

class _$AnalysisSerializer implements PrimitiveSerializer<Analysis> {
  @override
  final Iterable<Type> types = const [Analysis, _$Analysis];

  @override
  final String wireName = r'Analysis';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    Analysis object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'id';
    yield serializers.serialize(
      object.id,
      specifiedType: const FullType(int),
    );
    yield r'userId';
    yield serializers.serialize(
      object.userId,
      specifiedType: const FullType(int),
    );
    yield r'instrument';
    yield serializers.serialize(
      object.instrument,
      specifiedType: const FullType(String),
    );
    yield r'timeframe';
    yield serializers.serialize(
      object.timeframe,
      specifiedType: const FullType(String),
    );
    if (object.userInputContext != null) {
      yield r'userInputContext';
      yield serializers.serialize(
        object.userInputContext,
        specifiedType: const FullType(String),
      );
    }
    yield r'mode';
    yield serializers.serialize(
      object.mode,
      specifiedType: const FullType(AnalysisModeEnum),
    );
    yield r'validUntil';
    yield serializers.serialize(
      object.validUntil,
      specifiedType: const FullType(DateTime),
    );
    if (object.marketCondition != null) {
      yield r'marketCondition';
      yield serializers.serialize(
        object.marketCondition,
        specifiedType: const FullType(String),
      );
    }
    if (object.riskLevel != null) {
      yield r'riskLevel';
      yield serializers.serialize(
        object.riskLevel,
        specifiedType: const FullType(String),
      );
    }
    if (object.confidenceMin != null) {
      yield r'confidenceMin';
      yield serializers.serialize(
        object.confidenceMin,
        specifiedType: const FullType(int),
      );
    }
    if (object.confidenceMax != null) {
      yield r'confidenceMax';
      yield serializers.serialize(
        object.confidenceMax,
        specifiedType: const FullType(int),
      );
    }
    if (object.mainScenario != null) {
      yield r'mainScenario';
      yield serializers.serialize(
        object.mainScenario,
        specifiedType: const FullType(String),
      );
    }
    if (object.alternativeScenario != null) {
      yield r'alternativeScenario';
      yield serializers.serialize(
        object.alternativeScenario,
        specifiedType: const FullType(String),
      );
    }
    if (object.whyReason != null) {
      yield r'whyReason';
      yield serializers.serialize(
        object.whyReason,
        specifiedType: const FullType(String),
      );
    }
    if (object.failureConditions != null) {
      yield r'failureConditions';
      yield serializers.serialize(
        object.failureConditions,
        specifiedType: const FullType(String),
      );
    }
    if (object.baseCase != null) {
      yield r'baseCase';
      yield serializers.serialize(
        object.baseCase,
        specifiedType: const FullType(String),
      );
    }
    if (object.bullishScenario != null) {
      yield r'bullishScenario';
      yield serializers.serialize(
        object.bullishScenario,
        specifiedType: const FullType(String),
      );
    }
    if (object.bearishScenario != null) {
      yield r'bearishScenario';
      yield serializers.serialize(
        object.bearishScenario,
        specifiedType: const FullType(String),
      );
    }
    if (object.keyDriversTechnical != null) {
      yield r'keyDriversTechnical';
      yield serializers.serialize(
        object.keyDriversTechnical,
        specifiedType: const FullType(String),
      );
    }
    if (object.keyDriversFundamental != null) {
      yield r'keyDriversFundamental';
      yield serializers.serialize(
        object.keyDriversFundamental,
        specifiedType: const FullType(String),
      );
    }
    if (object.marketContext != null) {
      yield r'marketContext';
      yield serializers.serialize(
        object.marketContext,
        specifiedType: const FullType(String),
      );
    }
    if (object.invalidationConditions != null) {
      yield r'invalidationConditions';
      yield serializers.serialize(
        object.invalidationConditions,
        specifiedType: const FullType(String),
      );
    }
    if (object.uncertaintyNotes != null) {
      yield r'uncertaintyNotes';
      yield serializers.serialize(
        object.uncertaintyNotes,
        specifiedType: const FullType(String),
      );
    }
    if (object.tradingBias != null) {
      yield r'tradingBias';
      yield serializers.serialize(
        object.tradingBias,
        specifiedType: const FullType(String),
      );
    }
    if (object.opportunity != null) {
      yield r'opportunity';
      yield serializers.serialize(
        object.opportunity,
        specifiedType: const FullType(String),
      );
    }
    if (object.risk != null) {
      yield r'risk';
      yield serializers.serialize(
        object.risk,
        specifiedType: const FullType(String),
      );
    }
    if (object.techBuyCount != null) {
      yield r'techBuyCount';
      yield serializers.serialize(
        object.techBuyCount,
        specifiedType: const FullType(int),
      );
    }
    if (object.techSellCount != null) {
      yield r'techSellCount';
      yield serializers.serialize(
        object.techSellCount,
        specifiedType: const FullType(int),
      );
    }
    if (object.techNeutralCount != null) {
      yield r'techNeutralCount';
      yield serializers.serialize(
        object.techNeutralCount,
        specifiedType: const FullType(int),
      );
    }
    if (object.tradePlan != null) {
      yield r'tradePlan';
      yield serializers.serialize(
        object.tradePlan,
        specifiedType: const FullType(TradePlan),
      );
    }
    if (object.fundamentalContext != null) {
      yield r'fundamentalContext';
      yield serializers.serialize(
        object.fundamentalContext,
        specifiedType: const FullType(FundamentalContext),
      );
    }
    if (object.fundamentalCitations != null) {
      yield r'fundamentalCitations';
      yield serializers.serialize(
        object.fundamentalCitations,
        specifiedType: const FullType(FundamentalCitations),
      );
    }
    if (object.outcomeStatus != null) {
      yield r'outcomeStatus';
      yield serializers.serialize(
        object.outcomeStatus,
        specifiedType: const FullType(AnalysisOutcomeStatusEnum),
      );
    }
    if (object.outcomeResolvedAt != null) {
      yield r'outcomeResolvedAt';
      yield serializers.serialize(
        object.outcomeResolvedAt,
        specifiedType: const FullType(DateTime),
      );
    }
    if (object.outcomeCheckedAt != null) {
      yield r'outcomeCheckedAt';
      yield serializers.serialize(
        object.outcomeCheckedAt,
        specifiedType: const FullType(DateTime),
      );
    }
    if (object.userNote != null) {
      yield r'userNote';
      yield serializers.serialize(
        object.userNote,
        specifiedType: const FullType(String),
      );
    }
    if (object.userNoteUpdatedAt != null) {
      yield r'userNoteUpdatedAt';
      yield serializers.serialize(
        object.userNoteUpdatedAt,
        specifiedType: const FullType(DateTime),
      );
    }
    if (object.hasNote != null) {
      yield r'hasNote';
      yield serializers.serialize(
        object.hasNote,
        specifiedType: const FullType(bool),
      );
    }
    if (object.feedback != null) {
      yield r'feedback';
      yield serializers.serialize(
        object.feedback,
        specifiedType: const FullType(Feedback),
      );
    }
    if (object.usefulCount != null) {
      yield r'usefulCount';
      yield serializers.serialize(
        object.usefulCount,
        specifiedType: const FullType(int),
      );
    }
    if (object.notUsefulCount != null) {
      yield r'notUsefulCount';
      yield serializers.serialize(
        object.notUsefulCount,
        specifiedType: const FullType(int),
      );
    }
    yield r'createdAt';
    yield serializers.serialize(
      object.createdAt,
      specifiedType: const FullType(DateTime),
    );
  }

  @override
  Object serialize(
    Serializers serializers,
    Analysis object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required AnalysisBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(int),
          ) as int;
          result.id = valueDes;
          break;
        case r'userId':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(int),
          ) as int;
          result.userId = valueDes;
          break;
        case r'instrument':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.instrument = valueDes;
          break;
        case r'timeframe':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.timeframe = valueDes;
          break;
        case r'userInputContext':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.userInputContext = valueDes;
          break;
        case r'mode':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(AnalysisModeEnum),
          ) as AnalysisModeEnum;
          result.mode = valueDes;
          break;
        case r'validUntil':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(DateTime),
          ) as DateTime;
          result.validUntil = valueDes;
          break;
        case r'marketCondition':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.marketCondition = valueDes;
          break;
        case r'riskLevel':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.riskLevel = valueDes;
          break;
        case r'confidenceMin':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(int),
          ) as int?;
          if (valueDes == null) continue;
          result.confidenceMin = valueDes;
          break;
        case r'confidenceMax':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(int),
          ) as int?;
          if (valueDes == null) continue;
          result.confidenceMax = valueDes;
          break;
        case r'mainScenario':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.mainScenario = valueDes;
          break;
        case r'alternativeScenario':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.alternativeScenario = valueDes;
          break;
        case r'whyReason':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.whyReason = valueDes;
          break;
        case r'failureConditions':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.failureConditions = valueDes;
          break;
        case r'baseCase':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.baseCase = valueDes;
          break;
        case r'bullishScenario':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.bullishScenario = valueDes;
          break;
        case r'bearishScenario':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.bearishScenario = valueDes;
          break;
        case r'keyDriversTechnical':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.keyDriversTechnical = valueDes;
          break;
        case r'keyDriversFundamental':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.keyDriversFundamental = valueDes;
          break;
        case r'marketContext':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.marketContext = valueDes;
          break;
        case r'invalidationConditions':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.invalidationConditions = valueDes;
          break;
        case r'uncertaintyNotes':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.uncertaintyNotes = valueDes;
          break;
        case r'tradingBias':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.tradingBias = valueDes;
          break;
        case r'opportunity':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.opportunity = valueDes;
          break;
        case r'risk':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.risk = valueDes;
          break;
        case r'techBuyCount':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(int),
          ) as int?;
          if (valueDes == null) continue;
          result.techBuyCount = valueDes;
          break;
        case r'techSellCount':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(int),
          ) as int?;
          if (valueDes == null) continue;
          result.techSellCount = valueDes;
          break;
        case r'techNeutralCount':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(int),
          ) as int?;
          if (valueDes == null) continue;
          result.techNeutralCount = valueDes;
          break;
        case r'tradePlan':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(TradePlan),
          ) as TradePlan?;
          if (valueDes == null) continue;
          result.tradePlan.replace(valueDes);
          break;
        case r'fundamentalContext':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(FundamentalContext),
          ) as FundamentalContext?;
          if (valueDes == null) continue;
          result.fundamentalContext.replace(valueDes);
          break;
        case r'fundamentalCitations':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(FundamentalCitations),
          ) as FundamentalCitations?;
          if (valueDes == null) continue;
          result.fundamentalCitations.replace(valueDes);
          break;
        case r'outcomeStatus':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(AnalysisOutcomeStatusEnum),
          ) as AnalysisOutcomeStatusEnum?;
          if (valueDes == null) continue;
          result.outcomeStatus = valueDes;
          break;
        case r'outcomeResolvedAt':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(DateTime),
          ) as DateTime?;
          if (valueDes == null) continue;
          result.outcomeResolvedAt = valueDes;
          break;
        case r'outcomeCheckedAt':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(DateTime),
          ) as DateTime?;
          if (valueDes == null) continue;
          result.outcomeCheckedAt = valueDes;
          break;
        case r'userNote':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.userNote = valueDes;
          break;
        case r'userNoteUpdatedAt':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(DateTime),
          ) as DateTime?;
          if (valueDes == null) continue;
          result.userNoteUpdatedAt = valueDes;
          break;
        case r'hasNote':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(bool),
          ) as bool?;
          if (valueDes == null) continue;
          result.hasNote = valueDes;
          break;
        case r'feedback':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(Feedback),
          ) as Feedback?;
          if (valueDes == null) continue;
          result.feedback.replace(valueDes);
          break;
        case r'usefulCount':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(int),
          ) as int?;
          if (valueDes == null) continue;
          result.usefulCount = valueDes;
          break;
        case r'notUsefulCount':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(int),
          ) as int?;
          if (valueDes == null) continue;
          result.notUsefulCount = valueDes;
          break;
        case r'createdAt':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(DateTime),
          ) as DateTime;
          result.createdAt = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  Analysis deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = AnalysisBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

class AnalysisModeEnum extends EnumClass {

  @BuiltValueEnumConst(wireName: r'beginner')
  static const AnalysisModeEnum beginner = _$analysisModeEnum_beginner;
  @BuiltValueEnumConst(wireName: r'pro')
  static const AnalysisModeEnum pro = _$analysisModeEnum_pro;

  static Serializer<AnalysisModeEnum> get serializer => _$analysisModeEnumSerializer;

  const AnalysisModeEnum._(String name): super(name);

  static BuiltSet<AnalysisModeEnum> get values => _$analysisModeEnumValues;
  static AnalysisModeEnum valueOf(String name) => _$analysisModeEnumValueOf(name);
}

class AnalysisOutcomeStatusEnum extends EnumClass {

  /// After-the-fact resolution of the AI's trade plan. `pending` until the background resolver finishes scoring it; `tp1_hit`/`tp2_hit` if price reached the corresponding take-profit; `sl_hit` if the stop-loss was touched first; `expired` if the validity window passed with no trigger touched; `invalidated` when the plan levels were unparseable or internally inconsistent.
  @BuiltValueEnumConst(wireName: r'pending')
  static const AnalysisOutcomeStatusEnum pending = _$analysisOutcomeStatusEnum_pending;
  /// After-the-fact resolution of the AI's trade plan. `pending` until the background resolver finishes scoring it; `tp1_hit`/`tp2_hit` if price reached the corresponding take-profit; `sl_hit` if the stop-loss was touched first; `expired` if the validity window passed with no trigger touched; `invalidated` when the plan levels were unparseable or internally inconsistent.
  @BuiltValueEnumConst(wireName: r'tp1_hit')
  static const AnalysisOutcomeStatusEnum tp1Hit = _$analysisOutcomeStatusEnum_tp1Hit;
  /// After-the-fact resolution of the AI's trade plan. `pending` until the background resolver finishes scoring it; `tp1_hit`/`tp2_hit` if price reached the corresponding take-profit; `sl_hit` if the stop-loss was touched first; `expired` if the validity window passed with no trigger touched; `invalidated` when the plan levels were unparseable or internally inconsistent.
  @BuiltValueEnumConst(wireName: r'tp2_hit')
  static const AnalysisOutcomeStatusEnum tp2Hit = _$analysisOutcomeStatusEnum_tp2Hit;
  /// After-the-fact resolution of the AI's trade plan. `pending` until the background resolver finishes scoring it; `tp1_hit`/`tp2_hit` if price reached the corresponding take-profit; `sl_hit` if the stop-loss was touched first; `expired` if the validity window passed with no trigger touched; `invalidated` when the plan levels were unparseable or internally inconsistent.
  @BuiltValueEnumConst(wireName: r'sl_hit')
  static const AnalysisOutcomeStatusEnum slHit = _$analysisOutcomeStatusEnum_slHit;
  /// After-the-fact resolution of the AI's trade plan. `pending` until the background resolver finishes scoring it; `tp1_hit`/`tp2_hit` if price reached the corresponding take-profit; `sl_hit` if the stop-loss was touched first; `expired` if the validity window passed with no trigger touched; `invalidated` when the plan levels were unparseable or internally inconsistent.
  @BuiltValueEnumConst(wireName: r'expired')
  static const AnalysisOutcomeStatusEnum expired = _$analysisOutcomeStatusEnum_expired;
  /// After-the-fact resolution of the AI's trade plan. `pending` until the background resolver finishes scoring it; `tp1_hit`/`tp2_hit` if price reached the corresponding take-profit; `sl_hit` if the stop-loss was touched first; `expired` if the validity window passed with no trigger touched; `invalidated` when the plan levels were unparseable or internally inconsistent.
  @BuiltValueEnumConst(wireName: r'invalidated')
  static const AnalysisOutcomeStatusEnum invalidated = _$analysisOutcomeStatusEnum_invalidated;

  static Serializer<AnalysisOutcomeStatusEnum> get serializer => _$analysisOutcomeStatusEnumSerializer;

  const AnalysisOutcomeStatusEnum._(String name): super(name);

  static BuiltSet<AnalysisOutcomeStatusEnum> get values => _$analysisOutcomeStatusEnumValues;
  static AnalysisOutcomeStatusEnum valueOf(String name) => _$analysisOutcomeStatusEnumValueOf(name);
}

