import 'package:test/test.dart';
import 'package:trade_pilot_api_client/trade_pilot_api_client.dart';

// tests for Analysis
void main() {
  final instance = AnalysisBuilder();
  // TODO add properties to the builder and call build()

  group(Analysis, () {
    // int id
    test('to test the property `id`', () async {
      // TODO
    });

    // int userId
    test('to test the property `userId`', () async {
      // TODO
    });

    // String instrument
    test('to test the property `instrument`', () async {
      // TODO
    });

    // String timeframe
    test('to test the property `timeframe`', () async {
      // TODO
    });

    // String userInputContext
    test('to test the property `userInputContext`', () async {
      // TODO
    });

    // String mode
    test('to test the property `mode`', () async {
      // TODO
    });

    // DateTime validUntil
    test('to test the property `validUntil`', () async {
      // TODO
    });

    // String marketCondition
    test('to test the property `marketCondition`', () async {
      // TODO
    });

    // String riskLevel
    test('to test the property `riskLevel`', () async {
      // TODO
    });

    // int confidenceMin
    test('to test the property `confidenceMin`', () async {
      // TODO
    });

    // int confidenceMax
    test('to test the property `confidenceMax`', () async {
      // TODO
    });

    // String mainScenario
    test('to test the property `mainScenario`', () async {
      // TODO
    });

    // String alternativeScenario
    test('to test the property `alternativeScenario`', () async {
      // TODO
    });

    // String whyReason
    test('to test the property `whyReason`', () async {
      // TODO
    });

    // String failureConditions
    test('to test the property `failureConditions`', () async {
      // TODO
    });

    // String baseCase
    test('to test the property `baseCase`', () async {
      // TODO
    });

    // String bullishScenario
    test('to test the property `bullishScenario`', () async {
      // TODO
    });

    // String bearishScenario
    test('to test the property `bearishScenario`', () async {
      // TODO
    });

    // String keyDriversTechnical
    test('to test the property `keyDriversTechnical`', () async {
      // TODO
    });

    // String keyDriversFundamental
    test('to test the property `keyDriversFundamental`', () async {
      // TODO
    });

    // String marketContext
    test('to test the property `marketContext`', () async {
      // TODO
    });

    // String invalidationConditions
    test('to test the property `invalidationConditions`', () async {
      // TODO
    });

    // String uncertaintyNotes
    test('to test the property `uncertaintyNotes`', () async {
      // TODO
    });

    // Directional bias. One of: bearish_strong, bearish, neutral, bullish, bullish_strong. Legacy values (strong_sell, sell, buy, strong_buy) may exist on older rows and are normalized client-side.
    // String tradingBias
    test('to test the property `tradingBias`', () async {
      // TODO
    });

    // String opportunity
    test('to test the property `opportunity`', () async {
      // TODO
    });

    // String risk
    test('to test the property `risk`', () async {
      // TODO
    });

    // Snapshot of the technical-indicator buy tally captured at analysis time. Used to render the same Market Context Summary on the saved analysis page.
    // int techBuyCount
    test('to test the property `techBuyCount`', () async {
      // TODO
    });

    // Snapshot of the technical-indicator sell tally captured at analysis time.
    // int techSellCount
    test('to test the property `techSellCount`', () async {
      // TODO
    });

    // Snapshot of the technical-indicator neutral tally captured at analysis time.
    // int techNeutralCount
    test('to test the property `techNeutralCount`', () async {
      // TODO
    });

    // Structured trade plan with concrete buy and sell entry/SL/TP levels generated by the AI and anchored to the latest closing price. Nullable for legacy rows or when no anchor price was available.
    // TradePlan tradePlan
    test('to test the property `tradePlan`', () async {
      // TODO
    });

    // Snapshot of the news headlines + economic-calendar events the AI saw when this analysis was generated. Lets the saved-analysis page render the same fundamental context the model used. Nullable for legacy rows or when both upstream feeds were down.
    // FundamentalContext fundamentalContext
    test('to test the property `fundamentalContext`', () async {
      // TODO
    });

    // Which news headlines + calendar events the AI actually cited in its narrative. Drives the inline source chips next to the AI's reasoning blocks (whyReason / keyDriversFundamental / marketContext). Nullable for legacy rows + analyses where the AI didn't lean on any fundamental input.
    // FundamentalCitations fundamentalCitations
    test('to test the property `fundamentalCitations`', () async {
      // TODO
    });

    // After-the-fact resolution of the AI's trade plan. `pending` until the background resolver finishes scoring it; `tp1_hit`/`tp2_hit` if price reached the corresponding take-profit; `sl_hit` if the stop-loss was touched first; `expired` if the validity window passed with no trigger touched; `invalidated` when the plan levels were unparseable or internally inconsistent.
    // String outcomeStatus
    test('to test the property `outcomeStatus`', () async {
      // TODO
    });

    // Timestamp the trigger (SL/TP1/TP2) fired on, or the validity-window end for `expired`. Null while outcomeStatus is `pending`.
    // DateTime outcomeResolvedAt
    test('to test the property `outcomeResolvedAt`', () async {
      // TODO
    });

    // When the background resolver last looked at this row. Null until the first resolver pass touches it.
    // DateTime outcomeCheckedAt
    test('to test the property `outcomeCheckedAt`', () async {
      // TODO
    });

    // Private per-analysis trading journal note written by the owning user. Only populated by the single-analysis GET; the list endpoint exposes `hasNote` instead to keep payloads small. Never fed into the AI prompt.
    // String userNote
    test('to test the property `userNote`', () async {
      // TODO
    });

    // When `userNote` was last saved server-side. Null when no note has been written.
    // DateTime userNoteUpdatedAt
    test('to test the property `userNoteUpdatedAt`', () async {
      // TODO
    });

    // True when the user has written a non-empty `userNote` for this analysis. Returned by the list endpoint so the history page can show a 'journaled' icon without loading the full note body.
    // bool hasNote
    test('to test the property `hasNote`', () async {
      // TODO
    });

    // Feedback feedback
    test('to test the property `feedback`', () async {
      // TODO
    });

    // Number of \"useful\" feedback rows for this analysis. Only populated by admin endpoints.
    // int usefulCount
    test('to test the property `usefulCount`', () async {
      // TODO
    });

    // Number of \"not_useful\" feedback rows for this analysis. Only populated by admin endpoints.
    // int notUsefulCount
    test('to test the property `notUsefulCount`', () async {
      // TODO
    });

    // DateTime createdAt
    test('to test the property `createdAt`', () async {
      // TODO
    });

  });
}
